name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      custom_parameter:
        description: Custom parameter for the workflow
        required: true
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install
        run: yarn
      - name: Run ranking
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node ./src/index.js
          ./push.sh
