name: Schedule
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install
        run: yarn
      - name: Run ranking
        run: npm run ranking
